### ISSUE TITLE
Fails to build with Rust < 1.30

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/atk#6]
See https://gitlab.freedesktop.org/ebnerm/gstreamer-rs/-/jobs/44018. This needs a `use glib` at the top in both files.

```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> .cargo_cache/git/checkouts/atk-98261c164e2822cd/b8eef79/src/auto/window.rs:63:27
   |
63 | impl<O: IsA<Window> + IsA<glib::object::Object>> AtkWindowExt for O {
   |                           ^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
 --> .cargo_cache/git/checkouts/atk-98261c164e2822cd/b8eef79/src/attribute_set.rs:5:25
  |
5 | pub type AttributeSet = glib::translate::SList;
  |                         ^^^^

error: aborting due to 2 previous errors
```
